### ISSUE TITLE
Error in solidus 2.2 timestamp 

### ISSUE THREAD

**Issue by sechix** [vinsol/solidus_admin_insights#3]
Hello,
I have following errors executing insights reports
` PG::UndefinedFunction: ERROR:  function date_format(timestamp without time zone, unknown) does not exist`

`ERROR: function ifnull(numeric, numeric) does not exist LINE 1: ...ent", 0 AS "promotion_discount`

`PG::UndefinedFunction: ERROR: function strcmp(character varying, unknown) does not exist LINE 1: ...ct_name", "products"."slug" AS "product_slug", IF(STRCMP("va... ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts.`

**Comment by nimish-mehta** [comment]
@sechix That function call was specific to MySQL. We are working on postgres support. #4 when merged should fix this issue.

**Comment by sechix** [comment]
Ok, Perfect!!!!
Thanks
